# Initial Setup

In [1]:
import polars as pl 
import pandas as pd
from utils.general_purpose import get_feature_definitions, count_missing_data
from utils.validation import calculate_gini_stability_metric

In [2]:
# VARIABLES
TRAIN_DATA_PATH = "../data/csv_files/train/"
TEST_DATA_PATH = "../data/csv_files/test/"
FEATURE_DEF_PATH = "../data/feature_definitions.csv"

# With polars
POLARS_TRAIN_DATA_PATH = "../data/train/"
POLARS_TEST_DATA_PATH = "../data/test/"

In [3]:
# Set polars config
pl.Config.set_tbl_rows(-1)
pl.Config.set_tbl_cols(-1)
pl.Config.set_tbl_width_chars(-1)
# Set pandas config (the utils is made by pandas so we need this too)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

# Business Understanding

## Describtion

Consumer finance providers must accurately determine which clients can repay a loan and which cannot and data is key. If data science could help better predict one’s repayment capabilities, loans might become more accessible to those who may benefit from them the most.

**The Problem**: The scorecard's stability in the future is critical, as a sudden drop in performance means that loans will be issued to worse clients on average. The core of the issue is that **loan providers aren't able to spot potential problems any sooner than the first due dates of those loans are observable**. Given the time it takes to redevelop, validate, and implement the scorecard, **stability is highly desirable**.

**Keyword**: stability, accuracy

## Evaluation

The subscription is using the gini stability metric. A gini score is calculated for predictions corresponding to each WEEK_NUM.
$$
    \text{Gini} = 2 \times \text{AUC} - 1
$$
A linear regression, $f(x) = a \cdot x + b$ is fit through the weekly gini score, and a falling_rate is calculated as $min(0,a)$. This is used to penalize models that drop off in predictive ability.

Finally, the variability of the predictions are calculated by taking the standard deviation of the residuals from the above linear regression, applying a penalty to model variablity.

Final metric is calculated as: 
$$
    \text{stability metric} = \mu(gini) + 88.0 \cdot min(0,a) - 0.5 \cdot \sigma(residuals)
$$

# Data Understanding

## Data Depth 0

### Train Base

In [4]:
# Get the columns 
train_base_feature = get_feature_definitions(data_file_path=TRAIN_DATA_PATH+"train_base.csv",
                                             feature_definitions_csv=FEATURE_DEF_PATH)
train_base_feature

Empty DataFrame
Columns: [Variable, Description, Data Type]
Index: []

In [5]:
# Read train base 
train_base = pl.read_parquet(POLARS_TRAIN_DATA_PATH+"train_base.parquet")

In [6]:
train_base.head()

shape: (5, 5)
┌─────────┬───────────────┬────────┬──────────┬────────┐
│ case_id ┆ date_decision ┆ MONTH  ┆ WEEK_NUM ┆ target │
│ ---     ┆ ---           ┆ ---    ┆ ---      ┆ ---    │
│ i64     ┆ str           ┆ i64    ┆ i64      ┆ i64    │
╞═════════╪═══════════════╪════════╪══════════╪════════╡
│ 0       ┆ 2019-01-03    ┆ 201901 ┆ 0        ┆ 0      │
│ 1       ┆ 2019-01-03    ┆ 201901 ┆ 0        ┆ 0      │
│ 2       ┆ 2019-01-04    ┆ 201901 ┆ 0        ┆ 0      │
│ 3       ┆ 2019-01-03    ┆ 201901 ┆ 0        ┆ 0      │
│ 4       ┆ 2019-01-04    ┆ 201901 ┆ 0        ┆ 1      │
└─────────┴───────────────┴────────┴──────────┴────────┘

In [7]:
train_base.describe()

shape: (9, 6)
┌────────────┬───────────────┬───────────────┬───────────────┬────────────┬────────────┐
│ statistic  ┆ case_id       ┆ date_decision ┆ MONTH         ┆ WEEK_NUM   ┆ target     │
│ ---        ┆ ---           ┆ ---           ┆ ---           ┆ ---        ┆ ---        │
│ str        ┆ f64           ┆ str           ┆ f64           ┆ f64        ┆ f64        │
╞════════════╪═══════════════╪═══════════════╪═══════════════╪════════════╪════════════╡
│ count      ┆ 1.526659e6    ┆ 1526659       ┆ 1.526659e6    ┆ 1.526659e6 ┆ 1.526659e6 │
│ null_count ┆ 0.0           ┆ 0             ┆ 0.0           ┆ 0.0        ┆ 0.0        │
│ mean       ┆ 1.2861e6      ┆ null          ┆ 201936.287982 ┆ 40.769036  ┆ 0.031437   │
│ std        ┆ 718946.592285 ┆ null          ┆ 44.735975     ┆ 23.797981  ┆ 0.174496   │
│ min        ┆ 0.0           ┆ 2019-01-01    ┆ 201901.0      ┆ 0.0        ┆ 0.0        │
│ 25%        ┆ 766198.0      ┆ null          ┆ 201906.0      ┆ 23.0       ┆ 0.0        │
│ 50%        ┆ 1.357358e6    ┆ null          ┆ 201910.0      ┆ 40.0       ┆ 0.0        │
│ 75%        ┆ 1.739023e6    ┆ null          ┆ 202001.0      ┆ 55.0       ┆ 0.0        │
│ max        ┆ 2.703454e6    ┆ 2020-10-05    ┆ 202010.0      ┆ 91.0       ┆ 1.0        │
└────────────┴───────────────┴───────────────┴───────────────┴────────────┴────────────┘

Insights:
- There is no null data
- Unique case ID (which is ok)
- Around 2 years worth of data, 
- Lots of week num, 91 week as max,
- Target is binary variable - if 0 then no default, if 1 then default

**Conclusion**: This table is like a fact table.

### Train static dataset

Remember that the train static is the internal dataset

In [8]:
# Get the feature definitions 
train_static_feature = get_feature_definitions(data_file_path=TRAIN_DATA_PATH+"train_static_0_0.csv",
                                             feature_definitions_csv=FEATURE_DEF_PATH)
train_static_feature

,Variable,Description,Data Type
1,actualdpdtolerance_344P,DPD of client with tolerance.,float64
14,amtinstpaidbefduel24m_4187115A,Number of instalments paid before due date in the last 24 months.,float64
17,annuity_780A,Monthly annuity amount.,float64
19,annuitynextmonth_57A,Next month's amount of annuity.,float64
20,applicationcnt_361L,Number of applications associated with the same email address as the client.,float64
21,applications30d_658L,Number of applications made by the client in the last 30 days.,float64
22,applicationscnt_1086L,Number of applications associated with the same phone number.,float64
23,applicationscnt_464L,Number of applications made in the last 30 days by other clients with the same employer as the applicant.,float64
24,applicationscnt_629L,Number of applications with the same employer in the last 7 days.,float64
25,applicationscnt_867L,Number of applications associated with the same mobile phone.,float64
30,avgdbddpdlast24m_3658932P,Average days past or before due of payment during the last 24 months.,float64
31,avgdbddpdlast3m_4187120P,Average days past or before due of payment during the last 3 months.,float64
32,avgdbdtollast24m_4525197P,Average days of payment before due date within the last 24 months (with tolerance).,float64
33,avgdpdtolclosure24_3658938P,"Average DPD (days past due) with tolerance within the past 24 months from the maximum closure date, assuming that the contract is finished. If the contract is ongoing, the calculation is based on the current date.",float64
34,avginstallast24m_3658937A,Average instalments paid by the client over the past 24 months.,float64
35,avglnamtstart24m_4525187A,Average loan amount in the last 24 months.,float64
36,avgmaxdpdlast9m_3716943P,Average Days Past Due (DPD) of the client in last 9 months.,float64
37,avgoutstandbalancel6m_4187114A,Average outstanding balance of applicant for the last 6 months.,float64
38,avgpmtlast12m_4525200A,Average of payments made by the client in the last 12 months.,float64
39,bankacctype_710L,Type of applicant's bank account.,object
46,cardtype_51L,Type of credit card.,object
52,clientscnt_100L,Number of applications with matching employer's phone and client's.,float64
53,clientscnt_1022L,Number of clients sharing the same mobile phone.,float64
54,clientscnt_1071L,Number of applications where the alternative phone number matches that of the client.,float64
55,clientscnt_1130L,Number of applications where client's phone number matches the alternative phone contact.,float64
56,clientscnt_136L,Number of applications associated with same email address as client's email.,float64
57,clientscnt_157L,Number of clients whose employer has the same phone number as the client.,float64
58,clientscnt_257L,Number of clients that share an alternative phone number with the applicant.,float64
59,clientscnt_304L,Number of clients with the same phone number.,float64
60,clientscnt_360L,Number of clients that have the same alternative phone number and employer's phone number.,float64
61,clientscnt_493L,Number of clients with matching phone numbers for both the employer and the client.,float64
62,clientscnt_533L,Number of clients with same client's and alternative's phone number,float64
63,clientscnt_887L,Number of clients sharing the same employer's phone number.,float64
64,clientscnt_946L,Number of clients with matching mobile and employer's number.,float64
65,clientscnt12m_3712952L,Number of clients that have used the same mobile phone as the applicant in the past 12 months.,float64
66,clientscnt3m_3712950L,Number of clients who have the same mobile phone number in the last 3 months.,float64
67,clientscnt6m_3712949L,Total number of clients who have used the same mobile number in the last 6 months.,float64
68,cntincpaycont9m_3716944L,Number of incoming payments in the past 9 months.,float64
69,cntpmts24_3658933L,Number of months with any incoming payment in last 24 months.,float64
76,commnoinclast6m_3546845L,Number of communications indicating low income in the last six months.,float64
101,credamount_770A,Loan amount or credit card limit.,float64
110,credtype_322L,Type of credit.,object
112,currdebt_22A,Current debt amount of the client.,float64
114,currdebtcredtyperange_828A,Current amount of debt of the applicant.,float64
116,datefirstoffer_1144D,Date of first customer relationship management (CRM) offer.,object
117,datelastinstal40dpd_247D,Date of last instalment that was more than 40 days past due (DPD).,float64
118,datelastunpaid_3546854D,Date of the last unpaid instalment.,object
131,daysoverduetolerancedd_3976961L,Number of days that past after the due date (with tolerance).,float64
137,deferredmnthsnum_166L,Number of deferred months.,float64
140,disbursedcredamount_1113A,Disbursed credit amount after consolidation.,float64
141,disbursementtype_67L,Type of disbursement.,object
143,downpmt_116A,Amount of downpayment.,float64
158,dtlastpmtallstes_4499206D,Date of last payment made by the applicant.,float64
163,eir_270L,Interest rate.,float64
174,equalitydataagreement_891L,"Flag indicating sudden changes in client's social-demographic data (e.g. education, family status, housing type).",object
175,equalityempfrom_62L,Flag indicating a sudden change in the client's length of employment.,object
180,firstclxcampaign_1125D,Date of the client's first campaign.,object
181,firstdatedue_489D,Date of the first due date.,object
202,homephncnt_628L,Number of distinct home phones on client's application.,float64
206,inittransactionamount_650A,Initial transaction amount of the credit application.,float64
207,inittransactioncode_186L,Transaction type of the initial credit transaction.,object
215,interestrate_311L,The interest rate of the active credit contract.,float64
217,interestrategrace_34L,Interest rate during the grace period.,float64
219,isbidproduct_1095L,Flag indicating if the product is a cross-sell.,bool
221,isbidproductrequest_292L,Flag indicating if the product is a cross-sell.,object
223,isdebitcard_729L,Flag indicating if the product is a debit card.,object
229,lastactivateddate_801D,Contract activation date for previous applications.,object
230,lastapplicationdate_877D,Date of previous customer's application.,object
231,lastapprcommoditycat_1041M,Commodity category of the last loan applications made by the applicant.,object
232,lastapprcommoditytypec_5251766M,Commodity type of the last application.,object
233,lastapprcredamount_781A,Credit amount from the client's last application.,float64
234,lastapprdate_640D,Date of approval on client's most recent previous application.,object
235,lastcancelreason_561M,Cancellation reason of the last application.,object
236,lastdelinqdate_224D,Date of the last delinquency occurrence.,object
237,lastdependentsnum_448L,Number of dependents in the client's last loan application.,float64
238,lastotherinc_902A,Amount of other income reported by the client in their last application.,float64
239,lastotherlnsexpense_631A,Monthly expenses on other loans from the last application.,float64
240,lastrejectcommoditycat_161M,Category of commodity in the applicant's last rejected application.,object
241,lastrejectcommodtypec_5251769M,Commodity type of the last rejected application.,object
242,lastrejectcredamount_222A,Credit amount on last rejected application.,float64
243,lastrejectdate_50D,Date of most recent rejected application by the applicant.,object
244,lastrejectreason_759M,Reason for rejection on the most recent rejected application.,object
245,lastrejectreasonclient_4145040M,Reason for the client's last loan rejection.,object
246,lastrepayingdate_696D,Date of the last payment made by the applicant.,float64
247,lastst_736L,Status of the client's previous credit application.,object
251,maininc_215A,Client's primary income amount.,float64
257,mastercontrelectronic_519L,Flag indicating the existence of the master contract for the client.,float64
258,mastercontrexist_109L,Flag indicating whether or not the applicant has an existing master contract.,float64
259,maxannuity_159A,Maximum annuity previously obtained by client.,float64
260,maxannuity_4075009A,Maximal annuity offered to the client in the current application.,float64
261,maxdbddpdlast1m_3658939P,Maximum number of days past due in the last month. A negative value indicates the number of days before the due date.,float64
262,maxdbddpdtollast12m_3658940P,Maximum number of days past due in last 12 months. A negative value implies days before due date.,float64
263,maxdbddpdtollast6m_4187119P,Maximum number of days past due in last 6 months. This predictor takes the value as a negative number when it represents days before due date.,float64
264,maxdebt4_972A,Maximal principal debt of the client in the history older than 4 months.,float64
266,maxdpdfrom6mto36m_3546853P,Maximum Days Past Due (DPD) in the period ranging from 6 to 36 months.,float64
267,maxdpdinstldate_3546855D,Date of instalment on which client was most days past due.,object
268,maxdpdinstlnum_3546846P,Instalment number of which client was most days past due.,float64
269,maxdpdlast12m_727P,Maximum days past due in the past 12 months.,float64
270,maxdpdlast24m_143P,Maximal days past due in the last 24 months.,float64
271,maxdpdlast3m_392P,Maximum number of days past due in last 3 months.,float64
272,maxdpdlast6m_474P,Maximum days past due in the last 6 months.,float64
273,maxdpdlast9m_1059P,Maximum days past due in last 9 months.,float64
274,maxdpdtolerance_374P,Maximum number of days past due (with tolerance).,float64
276,maxinstallast24m_3658928A,Maximum instalment in the last 24 months,float64
277,maxlnamtstart6m_4525199A,Maximum loan amount started in the last 6 months.,float64
278,maxoutstandbalancel12m_4187113A,Maximum outstanding balance in the last 12 months.,float64
279,maxpmtlast3m_4525190A,Maximum payment made by the client in the last 3 months.,float64
280,mindbddpdlast24m_3658935P,Minimum days past due (or days before due) in last 24 months.,float64
281,mindbdtollast24m_4525191P,Minimum days before due in last 24 months.,float64
282,mobilephncnt_593L,Number of persons with the same mobile phone number.,float64
285,monthsannuity_845L,Monthly annuity amount for the applicant.,float64
290,numactivecreds_622L,Number of active credits.,float64
291,numactivecredschannel_414L,Number of active credits.,float64
292,numactiverelcontr_750L,Number of active revolving credits.,float64
307,numcontrs3months_479L,Number of contracts in last 3 months.,float64
308,numincomingpmts_3546848L,Number of incoming payments.,float64
309,numinstlallpaidearly3d_817L,Number of instalments paid at least 3 days prior to their due date.,float64
310,numinstls_657L,Number of instalments.,float64
311,numinstlsallpaid_934L,Number of paid instalments.,float64
312,numinstlswithdpd10_728L,Number of instalments that were overdue for 10 or more days.,float64
313,numinstlswithdpd5_4187116L,Number of instalments that were overdue by at least 5 days.,float64
314,numinstlswithoutdpd_562L,Number of instalments that were not past due date.,float64
315,numinstmatpaidtearly2d_4499204L,Number of instalments that have been paid more than 2 days before their due date.,float64
316,numinstpaid_4499208L,Number of paid instalments.,float64
317,numinstpaidearly_338L,Number of installments paid prior to the due date.,float64
318,numinstpaidearly3d_3546850L,Number of instalments paid more than three days before the due date.,float64
319,numinstpaidearly3dest_4493216L,Number of instalments that have been paid more than 3 days in advance of the due date.,float64
320,numinstpaidearly5d_1087L,Number of instalments paid more than 5 days prior to the due date.,float64
321,numinstpaidearly5dest_4493211L,Number of instalments that were paid more than 5 days before the due date.,float64
322,numinstpaidearly5dobd_4499205L,Number of installments paid more than 5 days prior to the due date.,float64
323,numinstpaidearlyest_4493214L,Number of instalments paid before the due date.,float64
324,numinstpaidlastcontr_4325080L,Number of paid installments from the client's last contract.,float64
325,numinstpaidlate1d_3546852L,Number of instalments paid more than 1 day past their due date.,float64
326,numinstregularpaid_973L,Number of fully paid regular installments in the client's previous contracts.,float64
327,numinstregularpaidest_4493210L,Number of fully paid regular installments on clients' previous contracts.,float64
328,numinsttopaygr_769L,Number of unpaid instalments.,float64
329,numinsttopaygrest_4493213L,Number of unpaid instalments.,float64
330,numinstunpaidmax_3546851L,Maximum number of unpaid instalments.,float64
331,numinstunpaidmaxest_4493212L,Maximum number of unpaid instalments.,float64
332,numnotactivated_1143L,Number of non-activated credits.,float64
333,numpmtchanneldd_318L,Number of previous loan contracts for the applicant that had direct debit as payment channel.,float64
334,numrejects9m_859L,Number of credit applications that were rejected in the last 9 months.,float64
335,opencred_647L,Number of active loans from the previous application.,object
356,paytype_783L,Type of payment.,object
357,paytype1st_925L,Type of first payment of the client.,object
358,payvacationpostpone_4187118D,Date of last payment holiday instalment.,float64
359,pctinstlsallpaidearl3d_427L,Percentage of installments paid at least 3 days prior to the due date.,float64
360,pctinstlsallpaidlat10d_839L,Percentage of installments that were paid 10 or more days after the due date.,float64
361,pctinstlsallpaidlate1d_3546856L,Percentage of installments that are paid 1 or more days after the due date.,float64
362,pctinstlsallpaidlate4d_3546849L,Percentage of installments that were paid 4 or more days past their due date.,float64
363,pctinstlsallpaidlate6d_3546844L,Percentage of installments that were paid 6 or more days past their due date.,float64
380,pmtnum_254L,Total number of loan payments made by the client.,float64
396,posfpd10lastmonth_333P,Average FPD10 (Share of contracts with first installment past due more than 10 days) from point of sales that processed contract in the previous month.,float64
397,posfpd30lastmonth_3976960P,Average FPD30 (Share of contracts with first installment past due more than 30 days) from point of sales that processed contract in the previous month.,float64
398,posfstqpd30lastmonth_3976962P,"Average FSTPD30 (share of contracts with first, second, or third installment past due more than 30 days) from point of sale that processed contract in the last month.",float64
400,previouscontdistrict_112M,Contact district of the client's previous approved application.,object
401,price_1097A,Credit price.,float64
436,sellerplacecnt_915L,Number of sellerplaces where the same client's document was used.,float64
437,sellerplacescnt_216L,Number of sellerplaces where the same client's mobile phone was used.,float64
446,sumoutstandtotal_3546847A,Sum of total outstanding amount.,float64
447,sumoutstandtotalest_4493215A,Sum of total outstanding amount.,float64
454,totaldebt_9A,Total amount of debt.,float64
459,totalsettled_863A,Sum of all payments made by the client.,float64
460,totinstallast1m_4525188A,Total amount of monthly instalments paid in the previous month.,float64
461,twobodfilling_608L,Type of application process.,object
463,typesuite_864L,Persons accompanying the client during the loan application process.,object
464,validfrom_1069D,Date since the client has an active campaign.,float64

This is the DEPTH 0 type, which mean that this is the feature that can directly be used in machine learning model

In [9]:
train_static_0 = pl.read_parquet(POLARS_TRAIN_DATA_PATH+"train_static_0_0.parquet")
print(train_static_0.shape)
train_static_1 = pl.read_parquet(POLARS_TRAIN_DATA_PATH+"train_static_0_1.parquet")
print(train_static_1.shape)

(1003757, 168)
(522902, 168)

Now let concat these 2 tables

In [10]:
train_static = pl.concat([train_static_0, train_static_1], how="vertical")
train_static.shape

(1526659, 168)

The value here is the same as the train_base, which mean that we can join them.

In [11]:
train_static.describe()

shape: (9, 169)
┌────────────┬───────────────┬─────────────────────────┬────────────────────────────────┬──────────────┬──────────────────────┬─────────────────────┬──────────────────────┬───────────────────────┬──────────────────────┬──────────────────────┬──────────────────────┬───────────────────────────┬──────────────────────────┬───────────────────────────┬─────────────────────────────┬───────────────────────────┬───────────────────────────┬──────────────────────────┬────────────────────────────────┬────────────────────────┬──────────────────┬──────────────┬────────────────────────┬───────────────────────┬───────────────────────┬─────────────────┬──────────────────┬──────────────────┬──────────────────┬─────────────────┬─────────────────┬─────────────────┬─────────────────┬─────────────────┬─────────────────┬─────────────────┬─────────────────┬─────────────────┬──────────────────────────┬────────────────────┬──────────────────────────┬─────────────────┬───────────────┬──────────────┬────────────────────────────┬──────────────────────┬──────────────────────────┬─────────────────────────┬─────────────────────────────────┬───────────────────────┬───────────────────────────┬──────────────────────┬──────────────┬───────────────────────────┬────────────┬────────────────────────────┬─────────────────────┬────────────────────────┬───────────────────┬─────────────────┬────────────────────────────┬──────────────────────────┬───────────────────┬───────────────────────┬────────────────────┬──────────────────────────┬──────────────────┬────────────────────────┬──────────────────────────┬────────────────────────────┬─────────────────────────────────┬─────────────────────────┬───────────────────┬───────────────────────┬─────────────────────┬────────────────────────┬───────────────────┬──────────────────────────┬─────────────────────────────┬────────────────────────────────┬───────────────────────────┬────────────────────┬───────────────────────┬─────────────────────────────────┬───────────────────────┬─────────────┬──────────────┬────────────────────────────┬───────────────────────┬─────────────────┬─────────────────────┬──────────────────────────┬──────────────────────────────┬─────────────────────────────┬───────────────┬────────────────────────────┬──────────────────────────┬─────────────────────────┬────────────────────┬────────────────────┬───────────────────┬───────────────────┬────────────────────┬──────────────────────┬───────────────────────────┬──────────────────────────┬─────────────────────────────────┬───────────────────────┬───────────────────────────┬───────────────────────────┬───────────────────┬────────────────────┬─────────────────────┬────────────────────────────┬────────────────────────┬───────────────────────┬──────────────────────────┬─────────────────────────────┬────────────────┬───────────────────────┬─────────────────────────┬────────────────────────────┬──────────────────────────┬─────────────────────────────────┬──────────────────────┬─────────────────────────────┬────────────────────────────────┬──────────────────────────┬────────────────────────────────┬────────────────────────────────┬───────────────────────┬──────────────────────────────┬───────────────────────────────┬────────────────────────────┬─────────────────────────┬────────────────────────────────┬─────────────────────┬────────────────────────────┬───────────────────────────┬──────────────────────────────┬───────────────────────┬──────────────────────┬───────────────────┬───────────────┬─────────────────┬──────────────┬──────────────────────────────┬─────────────────────────────┬─────────────────────────────┬─────────────────────────────────┬─────────────────────────────────┬─────────────────────────────────┬─────────────┬────────────────────────┬────────────────────────────┬───────────────────────────────┬───────────────────────────┬──────────────┬─────────────────────┬──────────────────────┬───────────────────────────┬──────────────────────────────┬──────────────┬───────────────────┬──────────────────────────┬────────────────────┬────────────────┬─────────────────┐
│ statistic  ┆ case_id       ┆ actualdpdtolerance_344P ┆ amtinstpaidbefduel24m_4187115A ┆ annuity_780A ┆ annuitynextmonth_57A ┆ applicationcnt_361L ┆ applications30d_658L ┆ applicationscnt_1086L ┆ applicationscnt_464L ┆ applicationscnt_629L ┆ applicationscnt_867L ┆ avgdbddpdlast24m_3658932P ┆ avgdbddpdlast3m_4187120P ┆ avgdbdtollast24m_4525197P ┆ avgdpdtolclosure24_3658938P ┆ avginstallast24m_3658937A ┆ avglnamtstart24m_4525187A ┆ avgmaxdpdlast9m_3716943P ┆ avgoutstandbalancel6m_4187114A ┆ avgpmtlast12m_4525200A ┆ bankacctype_710L ┆ cardtype_51L ┆ clientscnt12m_3712952L ┆ clientscnt3m_3712950L ┆ clientscnt6m_3712949L ┆ clientscnt_100L ┆ clientscnt_1022L ┆ clientscnt_1071L ┆ clientscnt_1130L ┆ clientscnt_136L ┆ clientscnt_157L ┆ clientscnt_257L ┆ clientscnt_304L ┆ clientscnt_360L ┆ clientscnt_493L ┆ clientscnt_533L ┆ clientscnt_887L ┆ clientscnt_946L ┆ cntincpaycont9m_3716944L ┆ cntpmts24_3658933L ┆ commnoinclast6m_3546845L ┆ credamount_770A ┆ credtype_322L ┆ currdebt_22A ┆ currdebtcredtyperange_828A ┆ datefirstoffer_1144D ┆ datelastinstal40dpd_247D ┆ datelastunpaid_3546854D ┆ daysoverduetolerancedd_3976961… ┆ deferredmnthsnum_166L ┆ disbursedcredamount_1113A ┆ disbursementtype_67L ┆ downpmt_116A ┆ dtlastpmtallstes_4499206D ┆ eir_270L   ┆ equalitydataagreement_891L ┆ equalityempfrom_62L ┆ firstclxcampaign_1125D ┆ firstdatedue_489D ┆ homephncnt_628L ┆ inittransactionamount_650A ┆ inittransactioncode_186L ┆ interestrate_311L ┆ interestrategrace_34L ┆ isbidproduct_1095L ┆ isbidproductrequest_292L ┆ isdebitcard_729L ┆ lastactivateddate_801D ┆ lastapplicationdate_877D ┆ lastapprcommoditycat_1041M ┆ lastapprcommoditytypec_5251766… ┆ lastapprcredamount_781A ┆ lastapprdate_640D ┆ lastcancelreason_561M ┆ lastdelinqdate_224D ┆ lastdependentsnum_448L ┆ lastotherinc_902A ┆ lastotherlnsexpense_631A ┆ lastrejectcommoditycat_161M ┆ lastrejectcommodtypec_5251769M ┆ lastrejectcredamount_222A ┆ lastrejectdate_50D ┆ lastrejectreason_759M ┆ lastrejectreasonclient_4145040… ┆ lastrepayingdate_696D ┆ lastst_736L ┆ maininc_215A ┆ mastercontrelectronic_519L ┆ mastercontrexist_109L ┆ maxannuity_159A ┆ maxannuity_4075009A ┆ maxdbddpdlast1m_3658939P ┆ maxdbddpdtollast12m_3658940P ┆ maxdbddpdtollast6m_4187119P ┆ maxdebt4_972A ┆ maxdpdfrom6mto36m_3546853P ┆ maxdpdinstldate_3546855D ┆ maxdpdinstlnum_3546846P ┆ maxdpdlast12m_727P ┆ maxdpdlast24m_143P ┆ maxdpdlast3m_392P ┆ maxdpdlast6m_474P ┆ maxdpdlast9m_1059P ┆ maxdpdtolerance_374P ┆ maxinstallast24m_3658928A ┆ maxlnamtstart6m_4525199A ┆ maxoutstandbalancel12m_4187113… ┆ maxpmtlast3m_4525190A ┆ mindbddpdlast24m_3658935P ┆ mindbdtollast24m_4525191P ┆ mobilephncnt_593L ┆ monthsannuity_845L ┆ numactivecreds_622L ┆ numactivecredschannel_414L ┆ numactiverelcontr_750L ┆ numcontrs3months_479L ┆ numincomingpmts_3546848L ┆ numinstlallpaidearly3d_817L ┆ numinstls_657L ┆ numinstlsallpaid_934L ┆ numinstlswithdpd10_728L ┆ numinstlswithdpd5_4187116L ┆ numinstlswithoutdpd_562L ┆ numinstmatpaidtearly2d_4499204… ┆ numinstpaid_4499208L ┆ numinstpaidearly3d_3546850L ┆ numinstpaidearly3dest_4493216L ┆ numinstpaidearly5d_1087L ┆ numinstpaidearly5dest_4493211L ┆ numinstpaidearly5dobd_4499205L ┆ numinstpaidearly_338L ┆ numinstpaidearlyest_4493214L ┆ numinstpaidlastcontr_4325080L ┆ numinstpaidlate1d_3546852L ┆ numinstregularpaid_973L ┆ numinstregularpaidest_4493210L ┆ numinsttopaygr_769L ┆ numinsttopaygrest_4493213L ┆ numinstunpaidmax_3546851L ┆ numinstunpaidmaxest_4493212L ┆ numnotactivated_1143L ┆ numpmtchanneldd_318L ┆ numrejects9m_859L ┆ opencred_647L ┆ paytype1st_925L ┆ paytype_783L ┆ payvacationpostpone_4187118D ┆ pctinstlsallpaidearl3d_427L ┆ pctinstlsallpaidlat10d_839L ┆ pctinstlsallpaidlate1d_3546856… ┆ pctinstlsallpaidlate4d_3546849… ┆ pctinstlsallpaidlate6d_3546844… ┆ pmtnum_254L ┆ posfpd10lastmonth_333P ┆ posfpd30lastmonth_3976960P ┆ posfstqpd30lastmonth_3976962P ┆ previouscontdistrict_112M ┆ price_1097A  ┆ sellerplacecnt_915L ┆ sellerplacescnt_216L ┆ sumoutstandtotal_3546847A ┆ sumoutstandtotalest_4493215A ┆ totaldebt_9A ┆ totalsettled_863A ┆ totinstallast1m_4525188A ┆ twobodfilling_608L ┆ typesuite_864L ┆ validfrom_1069D │
│ ---        ┆ ---           ┆ ---                     ┆ ---                            ┆ ---          ┆ ---                  ┆ ---                 ┆ ---                  ┆ ---                   ┆ ---                  ┆ ---                  ┆ ---                  ┆ ---                       ┆ ---                      ┆ ---                       ┆ ---                         ┆ ---                       ┆ ---                       ┆ ---                      ┆ ---                            ┆ ---                    ┆ ---              ┆ ---          ┆ ---                    ┆ ---                   ┆ ---                   ┆ ---             ┆ ---              ┆ ---              ┆ ---              ┆ ---             ┆ ---             ┆ ---             ┆ ---             ┆ ---             ┆ ---             ┆ ---             ┆ ---             ┆ ---             ┆ ---                      ┆ ---                ┆ ---                      ┆ ---             ┆ ---           ┆ ---          ┆ ---                        ┆ ---                  ┆ ---                      ┆ ---                     ┆ ---                             ┆ ---                   ┆ ---                       ┆ ---                  ┆ ---          ┆ ---                       ┆ ---        ┆ ---                        ┆ ---                 ┆ ---                    ┆ ---               ┆ ---             ┆ ---                        ┆ ---                      ┆ ---               ┆ ---                   ┆ ---                ┆ ---                      ┆ ---              ┆ ---                    ┆ ---                      ┆ ---                        ┆ ---                             ┆ ---                     ┆ ---               ┆ ---                   ┆ ---                 ┆ ---                    ┆ ---               ┆ ---                      ┆ ---                         ┆ ---                            ┆ ---                       ┆ ---                ┆ ---                   ┆ ---                             ┆ ---                   ┆ ---         ┆ ---          ┆ ---                        ┆ ---                   ┆ ---             ┆ ---                 ┆ ---                      ┆ ---                          ┆ ---                         ┆ ---           ┆ ---                        ┆ ---                      ┆ ---                     ┆ ---                ┆ ---                ┆ ---               ┆ ---               ┆ ---                ┆ ---                  ┆ ---                       ┆ ---                      ┆ ---                             ┆ ---                   ┆ ---                       ┆ ---                       ┆ ---               ┆ ---                ┆ ---                 ┆ ---                        ┆ ---                    ┆ ---                   ┆ ---                      ┆ ---                         ┆ ---            ┆ ---                   ┆ ---                     ┆ ---                        ┆ ---                      ┆ ---                             ┆ ---                  ┆ ---                         ┆ ---                            ┆ ---                      ┆ ---                            ┆ ---                            ┆ ---                   ┆ ---                          ┆ ---                           ┆ ---                        ┆ ---                     ┆ ---                            ┆ ---                 ┆ ---                        ┆ ---                       ┆ ---                          ┆ ---                   ┆ ---                  ┆ ---               ┆ ---           ┆ ---             ┆ ---          ┆ ---                          ┆ ---                         ┆ ---                         ┆ ---                             ┆ ---                             ┆ ---                             ┆ ---         ┆ ---                    ┆ ---                        ┆ ---                           ┆ ---                       ┆ ---          ┆ ---                 ┆ ---                  ┆ ---                       ┆ ---                          ┆ ---          ┆ ---               ┆ ---                      ┆ ---                ┆ ---            ┆ ---             │
│ str        ┆ f64           ┆ f64                     ┆ f64                            ┆ f64          ┆ f64                  ┆ f64                 ┆ f64                  ┆ f64                   ┆ f64                  ┆ f64                  ┆ f64                  ┆ f64                       ┆ f64                      ┆ f64                       ┆ f64                         ┆ f64                       ┆ f64                       ┆ f64                      ┆ f64                            ┆ f64                    ┆ str              ┆ str          ┆ f64                    ┆ f64                   ┆ f64                   ┆ f64             ┆ f64              ┆ f64              ┆ f64              ┆ f64             ┆ f64             ┆ f64             ┆ f64             ┆ f64             ┆ f64             ┆ f64             ┆ f64             ┆ f64             ┆ f64                      ┆ f64                ┆ f64                      ┆ f64             ┆ str           ┆ f64          ┆ f64                        ┆ str                  ┆ str                      ┆ str                     ┆ f64                             ┆ f64                   ┆ f64                       ┆ str                  ┆ f64          ┆ str                       ┆ f64        ┆ f64                        ┆ f64                 ┆ str                    ┆ str               ┆ f64             ┆ f64                        ┆ str                      ┆ f64               ┆ f64                   ┆ f64                ┆ f64                      ┆ f64              ┆ str                    ┆ str                      ┆ str                        ┆ str                             ┆ f64                     ┆ str               ┆ str                   ┆ str                 ┆ f64                    ┆ f64               ┆ f64                      ┆ str                         ┆ str                            ┆ f64                       ┆ str                ┆ str                   ┆ str                             ┆ str                   ┆ str         ┆ f64          ┆ f64                        ┆ f64                   ┆ f64             ┆ f64                 ┆ f64                      ┆ f64                          ┆ f64                         ┆ f64           ┆ f64                        ┆ str                      ┆ f64                     ┆ f64                ┆ f64                ┆ f64               ┆ f64               ┆ f64                ┆ f64                  ┆ f64                       ┆ f64                      ┆ f64                             ┆ f64                   ┆ f64                       ┆ f64                       ┆ f64               ┆ f64                ┆ f64                 ┆ f64                        ┆ f64                    ┆ f64                   ┆ f64                      ┆ f64                         ┆ f64            ┆ f64                   ┆ f64                     ┆ f64                        ┆ f64                      ┆ f64                             ┆ f64                  ┆ f64                         ┆ f64                            ┆ f64                      ┆ f64                            ┆ f64                            ┆ f64                   ┆ f64                          ┆ f64                           ┆ f64                        ┆ f64                     ┆ f64                            ┆ f64                 ┆ f64                        ┆ f64                       ┆ f64                          ┆ f64                   ┆ f64                  ┆ f64               ┆ f64           ┆ str             ┆ str          ┆ str                          ┆ f64                         ┆ f64                         ┆ f64                             ┆ f64                             ┆ f64                             ┆ f64         ┆ f64                    ┆ f64                        ┆ f64                           ┆ str                       ┆ f64          ┆ f64                 ┆ f64                  ┆ f64                       ┆ f64                          ┆ f64          ┆ f64               ┆ f64                      ┆ str                ┆ str            ┆ str             │

In [12]:
train_static_missing_stats = count_missing_data(df=train_static)
train_static_missing_stats

                         Column Name  Missing Count  Missing Percentage
0                    clientscnt_136L        1526242           99.972685
1              lastrepayingdate_696D        1524282           99.844301
2                  lastotherinc_902A        1523603           99.799824
3           lastotherlnsexpense_631A        1523601           99.799693
4       payvacationpostpone_4187118D        1517330           99.388927
5           isbidproductrequest_292L        1514201           99.183970
6              interestrategrace_34L        1505776           98.632111
7             lastdependentsnum_448L        1497142           98.066562
8                equalityempfrom_62L        1488847           97.523219
9                maxannuity_4075009A        1450726           95.026198
10        equalitydataagreement_891L        1448632           94.889035
11          datelastinstal40dpd_247D        1392841           91.234585
12                   validfrom_1069D        1374886           90.058487
13         avglnamtstart24m_4525187A        1364150           89.355252
14                      cardtype_51L        1334968           87.443758
15                  isdebitcard_729L        1334357           87.403736
16        inittransactionamount_650A        1334357           87.403736
17          totinstallast1m_4525188A        1174211           76.913771
18             maxpmtlast3m_4525190A        1129330           73.973952
19                    typesuite_864L        1121505           73.461395
20                  bankacctype_710L        1109629           72.683487
21          maxlnamtstart6m_4525199A        1032856           67.654663
22            avgpmtlast12m_4525200A        1026987           67.270229
23               lastdelinqdate_224D         977975           64.059820
24         dtlastpmtallstes_4499206D         977119           64.003749
25         mindbdtollast24m_4525191P         972827           63.722613
26         avgdbdtollast24m_4525197P         972827           63.722613
27          maxdbddpdlast1m_3658939P         960953           62.944836
28          avgdbddpdlast3m_4187120P         948244           62.112364
29           datelastunpaid_3546854D         887659           58.143895
30       maxdbddpdtollast6m_4187119P         876276           57.398280
31            firstclxcampaign_1125D         859214           56.280676
32              numinstpaid_4499208L         847191           55.493139
33   numinstmatpaidtearly2d_4499204L         847191           55.493139
34    numinstpaidearly5dobd_4499205L         847191           55.493139
35    avgoutstandbalancel6m_4187114A         841181           55.099469
36        numinsttopaygrest_4493213L         840646           55.064425
37      numinstunpaidmaxest_4493212L         840646           55.064425
38    numinstregularpaidest_4493210L         840646           55.064425
39      sumoutstandtotalest_4493215A         840646           55.064425
40      numinstpaidearlyest_4493214L         840646           55.064425
41    numinstpaidearly5dest_4493211L         840646           55.064425
42    numinstpaidearly3dest_4493216L         840646           55.064425
43              datefirstoffer_1144D         833735           54.611737
44           maxdpdinstlnum_3546846P         829402           54.327915
45          maxdpdinstldate_3546855D         826000           54.105075
46         lastrejectcredamount_222A         769046           50.374445
47                lastrejectdate_50D         769046           50.374445
48   maxoutstandbalancel12m_4187113A         766958           50.237676
49          avgmaxdpdlast9m_3716943P         757006           49.585795
50      maxdbddpdtollast12m_3658940P         705504           46.212284
51     numinstpaidlastcontr_4325080L         669186           43.833364
52         avginstallast24m_3658937A         624875           40.930882
53         maxinstallast24m_3658928A         624875           40.930882
54         avgdbddpdlast24m_3658932P         613202           40.166272
55         mindbddpdlast24m_3658935P         613202           40.166272
56        numinstlswithdpd5_4187116L         561124           36.755032
57    amtinstpaidbefduel24m_4187115A         561124           36.755032
58                      maininc_215A         511255           33.488487
59                 firstdatedue_489D         482103           31.578958
60       avgdpdtolclosure24_3658938P         467175           30.601136
61       pctinstlsallpaidlat10d_839L         461362           30.220370
62                cntpmts24_3658933L         460822           30.184999
63   pctinstlsallpaidlate6d_3546844L         460079           30.136330
64   pctinstlsallpaidlate4d_3546849L         459827           30.119824
65       pctinstlsallpaidearl3d_427L         458738           30.048492
66   pctinstlsallpaidlate1d_3546856L         458738           30.048492
67          numinstlswithoutdpd_562L         456495           29.901569
68           numinstlswithdpd10_728L         456495           29.901569
69           numinstregularpaid_973L         455612           29.843731
70          cntincpaycont9m_3716944L         455190           29.816089
71          numincomingpmts_3546848L         455081           29.808949
72            lastactivateddate_801D         453587           29.711088
73               numinsttopaygr_769L         452594           29.646044
74         numinstunpaidmax_3546851L         452594           29.646044
75   daysoverduetolerancedd_3976961L         452594           29.646044
76          numinstpaidearly5d_1087L         452593           29.645979
77                monthsannuity_845L         452593           29.645979
78        numinstpaidlate1d_3546852L         452593           29.645979
79             numinstpaidearly_338L         452593           29.645979
80       numinstpaidearly3d_3546850L         446983           29.278509
81       numinstlallpaidearly3d_817L         445669           29.192439
82             numinstlsallpaid_934L         445669           29.192439
83         sumoutstandtotal_3546847A         445320           29.169579
84                 lastapprdate_640D         442041           28.954796
85           lastapprcredamount_781A         442041           28.954796
86           actualdpdtolerance_344P         418178           27.391710
87        maxdpdfrom6mto36m_3546853P         343375           22.491925
88          commnoinclast6m_3546845L         343375           22.491925
89                     maxdebt4_972A         306019           20.045013
90        mastercontrelectronic_519L         306019           20.045013
91                maxdpdlast9m_1059P         306019           20.045013
92              maxdpdtolerance_374P         306019           20.045013
93                 maxdpdlast6m_474P         306019           20.045013
94                 maxdpdlast3m_392P         306019           20.045013
95                maxdpdlast24m_143P         306019           20.045013
96                maxdpdlast12m_727P         306019           20.045013
97             mastercontrexist_109L         306019           20.045013
98                   maxannuity_159A         306019           20.045013
99          lastapplicationdate_877D         305137           19.987240
100                    opencred_647L         305137           19.987240
101                      lastst_736L         305137           19.987240
102                      price_1097A         223240           14.622781
103                interestrate_311L         190833           12.500041
104                         eir_270L         190833           12.500041
105    posfstqpd30lastmonth_3976962P         181122           11.863946
106       posfpd30lastmonth_3976960P         131888            8.638995
107           posfpd10lastmonth_333P          78526            5.143650
108                     paytype_783L          58575            3.836810
109                  paytype1st_925L          58575            3.836810
110                      pmtnum_254L          44954            2.944600
111             disbursementtype_67L            866            0.056725
112               twobodfilling_608L             91            0.005961
113                   numinstls_657L              4            0.000262
114                totalsettled_863A              4            0.000262
115       currdebtcredtyperange_828A              4            0.000262
116             annuitynextmonth_57A              4            0.000262
117                     currdebt_22A              4            0.000262
118                     totaldebt_9A              3            0.000197
119                    credtype_322L              1            0.000066
120         inittransactioncode_186L              1            0.000066

Every feature that is missing more than 90% can be considered as redundant. Therefore we can remove them

In [13]:
from typing import Union
def missing_data_cutoff_with_threshold(df: Union[pd.DataFrame, pl.DataFrame], threshold: float) -> Union[pd.DataFrame, pl.DataFrame]:
    """
    Eliminates columns from a DataFrame (Pandas or Polars) that have a missingness
    percentage exceeding a specified threshold.

    Parameters:
    -----------
    df : Union[pd.DataFrame, pl.DataFrame]
        The input DataFrame, either a Pandas DataFrame or a Polars DataFrame.
    threshold : float
        The percentage threshold (e.g., 90.0 for 90%) above which columns
        will be dropped.

    Returns:
    --------
    Union[pd.DataFrame, pl.DataFrame]
        A new DataFrame with columns exceeding the threshold removed.
        The returned DataFrame will be of the same type as the input.
    """
    if not (0 <= threshold <= 100):
        raise ValueError("Threshold must be a percentage between 0 and 100.")

    # Get the missing data summary using our previous function
    missing_summary_df = count_missing_data(df)

    # Identify columns to drop based on the threshold
    columns_to_drop = missing_summary_df[
        missing_summary_df['Missing Percentage'] > threshold
    ]['Column Name'].tolist()

    if not columns_to_drop:
        print(f"No columns found with missing percentage above {threshold}%.")
        return df.copy() # Return a copy to avoid modifying the original DataFrame in place

    print(f"Dropping {len(columns_to_drop)} columns with missing percentage above {threshold}%:")
    for col in columns_to_drop:
        print(f"- {col}")

    # Perform the drop operation based on DataFrame type
    if isinstance(df, pd.DataFrame):
        new_df = df.drop(columns=columns_to_drop)
    elif isinstance(df, pl.DataFrame):
        # Polars has a direct .drop() method
        new_df = df.drop(columns_to_drop)
    else:
        # This case should ideally not be reached if count_missing_data also validated input
        raise TypeError("Input must be either a pandas.DataFrame or a polars.DataFrame.")

    return new_df

In [14]:
train_static_remove_missing = missing_data_cutoff_with_threshold(df=train_static, threshold=90.0)
train_static_remove_missing.shape

Dropping 13 columns with missing percentage above 90.0%:
- clientscnt_136L
- lastrepayingdate_696D
- lastotherinc_902A
- lastotherlnsexpense_631A
- payvacationpostpone_4187118D
- isbidproductrequest_292L
- interestrategrace_34L
- lastdependentsnum_448L
- equalityempfrom_62L
- maxannuity_4075009A
- equalitydataagreement_891L
- datelastinstal40dpd_247D
- validfrom_1069D

(1526659, 155)

In [16]:
train_static_remove_missing_stats = count_missing_data(df=train_static_remove_missing)
train_static_remove_missing_stats

                         Column Name  Missing Count  Missing Percentage
0          avglnamtstart24m_4525187A        1364150           89.355252
1                       cardtype_51L        1334968           87.443758
2                   isdebitcard_729L        1334357           87.403736
3         inittransactionamount_650A        1334357           87.403736
4           totinstallast1m_4525188A        1174211           76.913771
5              maxpmtlast3m_4525190A        1129330           73.973952
6                     typesuite_864L        1121505           73.461395
7                   bankacctype_710L        1109629           72.683487
8           maxlnamtstart6m_4525199A        1032856           67.654663
9             avgpmtlast12m_4525200A        1026987           67.270229
10               lastdelinqdate_224D         977975           64.059820
11         dtlastpmtallstes_4499206D         977119           64.003749
12         mindbdtollast24m_4525191P         972827           63.722613
13         avgdbdtollast24m_4525197P         972827           63.722613
14          maxdbddpdlast1m_3658939P         960953           62.944836
15          avgdbddpdlast3m_4187120P         948244           62.112364
16           datelastunpaid_3546854D         887659           58.143895
17       maxdbddpdtollast6m_4187119P         876276           57.398280
18            firstclxcampaign_1125D         859214           56.280676
19              numinstpaid_4499208L         847191           55.493139
20   numinstmatpaidtearly2d_4499204L         847191           55.493139
21    numinstpaidearly5dobd_4499205L         847191           55.493139
22    avgoutstandbalancel6m_4187114A         841181           55.099469
23    numinstregularpaidest_4493210L         840646           55.064425
24    numinstpaidearly3dest_4493216L         840646           55.064425
25    numinstpaidearly5dest_4493211L         840646           55.064425
26      sumoutstandtotalest_4493215A         840646           55.064425
27      numinstunpaidmaxest_4493212L         840646           55.064425
28      numinstpaidearlyest_4493214L         840646           55.064425
29        numinsttopaygrest_4493213L         840646           55.064425
30              datefirstoffer_1144D         833735           54.611737
31           maxdpdinstlnum_3546846P         829402           54.327915
32          maxdpdinstldate_3546855D         826000           54.105075
33                lastrejectdate_50D         769046           50.374445
34         lastrejectcredamount_222A         769046           50.374445
35   maxoutstandbalancel12m_4187113A         766958           50.237676
36          avgmaxdpdlast9m_3716943P         757006           49.585795
37      maxdbddpdtollast12m_3658940P         705504           46.212284
38     numinstpaidlastcontr_4325080L         669186           43.833364
39         avginstallast24m_3658937A         624875           40.930882
40         maxinstallast24m_3658928A         624875           40.930882
41         mindbddpdlast24m_3658935P         613202           40.166272
42         avgdbddpdlast24m_3658932P         613202           40.166272
43        numinstlswithdpd5_4187116L         561124           36.755032
44    amtinstpaidbefduel24m_4187115A         561124           36.755032
45                      maininc_215A         511255           33.488487
46                 firstdatedue_489D         482103           31.578958
47       avgdpdtolclosure24_3658938P         467175           30.601136
48       pctinstlsallpaidlat10d_839L         461362           30.220370
49                cntpmts24_3658933L         460822           30.184999
50   pctinstlsallpaidlate6d_3546844L         460079           30.136330
51   pctinstlsallpaidlate4d_3546849L         459827           30.119824
52       pctinstlsallpaidearl3d_427L         458738           30.048492
53   pctinstlsallpaidlate1d_3546856L         458738           30.048492
54           numinstlswithdpd10_728L         456495           29.901569
55          numinstlswithoutdpd_562L         456495           29.901569
56           numinstregularpaid_973L         455612           29.843731
57          cntincpaycont9m_3716944L         455190           29.816089
58          numincomingpmts_3546848L         455081           29.808949
59            lastactivateddate_801D         453587           29.711088
60         numinstunpaidmax_3546851L         452594           29.646044
61   daysoverduetolerancedd_3976961L         452594           29.646044
62               numinsttopaygr_769L         452594           29.646044
63          numinstpaidearly5d_1087L         452593           29.645979
64                monthsannuity_845L         452593           29.645979
65             numinstpaidearly_338L         452593           29.645979
66        numinstpaidlate1d_3546852L         452593           29.645979
67       numinstpaidearly3d_3546850L         446983           29.278509
68       numinstlallpaidearly3d_817L         445669           29.192439
69             numinstlsallpaid_934L         445669           29.192439
70         sumoutstandtotal_3546847A         445320           29.169579
71           lastapprcredamount_781A         442041           28.954796
72                 lastapprdate_640D         442041           28.954796
73           actualdpdtolerance_344P         418178           27.391710
74          commnoinclast6m_3546845L         343375           22.491925
75        maxdpdfrom6mto36m_3546853P         343375           22.491925
76                 maxdpdlast6m_474P         306019           20.045013
77                maxdpdlast9m_1059P         306019           20.045013
78                 maxdpdlast3m_392P         306019           20.045013
79                maxdpdlast24m_143P         306019           20.045013
80                maxdpdlast12m_727P         306019           20.045013
81                     maxdebt4_972A         306019           20.045013
82                   maxannuity_159A         306019           20.045013
83             mastercontrexist_109L         306019           20.045013
84        mastercontrelectronic_519L         306019           20.045013
85              maxdpdtolerance_374P         306019           20.045013
86                     opencred_647L         305137           19.987240
87          lastapplicationdate_877D         305137           19.987240
88                       lastst_736L         305137           19.987240
89                       price_1097A         223240           14.622781
90                 interestrate_311L         190833           12.500041
91                          eir_270L         190833           12.500041
92     posfstqpd30lastmonth_3976962P         181122           11.863946
93        posfpd30lastmonth_3976960P         131888            8.638995
94            posfpd10lastmonth_333P          78526            5.143650
95                   paytype1st_925L          58575            3.836810
96                      paytype_783L          58575            3.836810
97                       pmtnum_254L          44954            2.944600
98              disbursementtype_67L            866            0.056725
99                twobodfilling_608L             91            0.005961
100             annuitynextmonth_57A              4            0.000262
101                totalsettled_863A              4            0.000262
102                   numinstls_657L              4            0.000262
103                     currdebt_22A              4            0.000262
104       currdebtcredtyperange_828A              4            0.000262
105                     totaldebt_9A              3            0.000197
106                    credtype_322L              1            0.000066
107         inittransactioncode_186L              1            0.000066

# EDA